name: Lint
on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
          registry-url: https://registry.npmjs.org/
      - uses: actions/cache@v1
        with:
          path: node_modules
          key: yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-
      - run: yarn install --frozen-lockfile
      - run: yarn format
      - run: yarn lint:text
      - run: yarn lint:format
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Prettier
